services:
  db:
    image: postgres:latest
    container_name: nitbook_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nitbook_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"

volumes:
  db_data:
