/*
  Warnings:

  - The values [ADMINISTRATOR] on the enum `Role` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Role_new" AS ENUM ('DIRECTOR', 'ASSISTANT', 'CATALOGER', 'REFERENCE_LIBRARIAN', 'CIRCULATION_LIBRARIAN', 'ARCHIVIST', 'DIGITAL_LIBRARIAN', 'SYSTEMS_LIBRARIAN', 'ACQUISITIONS_LIBRARIAN', 'YOUTH_LIBRARIAN', 'LAW_LIBRARIAN', 'MEDICAL_LIBRARIAN', 'SCHOOL_LIBRARIAN', 'PUBLIC_SERVICES_LIBRARIAN', 'INTERLIBRARY_LOAN_LIBRARIAN', 'RESEARCH_LIBRARIAN', 'SERIALS_LIBRARIAN', 'SPECIAL_COLLECTIONS_LIBRARIAN', 'TECHNICAL_LIBRARIAN', 'EVENTS_COORDINATOR', 'VOLUNTEER_COORDINATOR');
ALTER TABLE "librarians" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "Role_old";
COMMIT;
